# Generated by Django 2.1.7 on 2019-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterroll', '0002_geocoderesult'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocoderesult',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
