# Generated by Django 2.1.7 on 2019-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterroll', '0003_geocoderesult_failed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geocoderesult',
            index=models.Index(fields=['failed'], name='voterroll_g_failed_07b5e3_idx'),
        ),
    ]
