# Generated by Django 2.1.7 on 2019-04-09 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voterroll', '0004_auto_20190408_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterrecord',
            name='block',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='county_fips',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='geocode_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='geocode_is_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='geocoded_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='tiger_line',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='tiger_side',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='tract',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
