# Generated by Django 2.2 on 2019-04-23 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("voterroll", "0009_county")]

    operations = [
        migrations.AlterField(
            model_name="county",
            name="poly",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        )
    ]
